name: super_text_editor_testing
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  super_editor: 
    git: 
      url: https://github.com/superlistapp/super_editor
      path: super_editor

  svg_highlight:
    path: svg_highlight

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
