name: svg_highlight
description: Parse an SVG file for syntax highlighting
version: 1.0.0

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  antlr4: ^4.11.1
  timing: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
